const confusingBrowserGlobals = require('confusing-browser-globals')

const allowedProperties = require('../utils/allowedProperties.js')

module.exports = {
  'accessor-pairs': 'error',
  'arrow-body-style': 'error',
  'block-scoped-var': 'error',
  camelcase: ['error', { allow: allowedProperties }],
  'capitalized-comments': [
    'error',
    'always',
    {
      ignoreConsecutiveComments: true,
      ignorePattern: /^\s*(c8|type-coverage:|webpack\w)/.source
    }
  ],
  'class-methods-use-this': 'error',
  complexity: 'off',
  'consistent-return': 'off',
  'consistent-this': 'error',
  curly: 'error',
  'default-case': 'error',
  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-notation': 'error',
  eqeqeq: ['error', 'always', { null: 'never' }],
  'func-name-matching': 'off',
  'func-names': 'error',
  'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
  'grouped-accessor-pairs': ['error', 'getBeforeSet'],
  'guard-for-in': 'error',
  'id-denylist': ['error', 'l', 'O', 'React'],
  'id-length': 'off',
  'id-match': 'off',
  'init-declarations': 'off',
  'logical-assignment-operators': ['off', 'always', { enforceForIfStatements: true }],
  'max-classes-per-file': 'off',
  'max-depth': 'off',
  'max-lines': 'off',
  'max-lines-per-function': 'off',
  'max-nested-callbacks': 'off',
  'max-params': 'off',
  'max-statements': 'off',
  'multiline-comment-style': 'off',
  'new-cap': 'error',
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-bitwise': 'off',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-confusing-arrow': 'off',
  'no-console': 'error',
  'no-continue': 'off',
  'no-delete-var': 'off',
  'no-div-regex': 'off',
  'no-else-return': ['error', { allowElseIf: false }],
  'no-empty': 'error',
  'no-empty-function': 'error',
  'no-empty-static-block': 'error',
  'no-eq-null': 'off',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-extra-semi': 'off',
  'no-floating-decimal': 'off',
  'no-global-assign': 'error',
  'no-implicit-coercion': ['error', { disallowTemplateShorthand: true }],
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-inline-comments': ['error', { ignorePattern: /\s@type\s/.source }],
  'no-invalid-this': 'off',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': ['error', { allowLoop: true }],
  'no-lone-blocks': 'error',
  'no-lonely-if': 'off',
  'no-loop-func': 'error',
  'no-magic-numbers': 'off',
  'no-mixed-operators': 'off',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'off',
  'no-nested-ternary': 'off',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-object': 'off',
  'no-new-wrappers': 'error',
  'no-nonoctal-decimal-escape': 'off',
  'no-object-constructor': 'error',
  'no-octal': 'off',
  'no-octal-escape': 'error',
  'no-param-reassign': [
    'error',
    {
      props: true,
      // Koa context.
      ignorePropertyModificationsFor: ['ctx']
    }
  ],
  'no-plusplus': 'error',
  'no-proto': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-restricted-exports': 'off',
  'no-restricted-globals': ['error', ...confusingBrowserGlobals.filter((name) => name !== 'self')],
  'no-restricted-imports': [
    'error',
    { name: 'node:assert', message: 'Use node:assert/strict instead.' },
    { name: 'node:test', importNames: ['it'], message: 'Use test instead.' },
    { name: 'node:dns', importNames: ['promises'], message: 'Use node:dns/promises instead.' },
    { name: 'node:fs', importNames: ['promises'], message: 'Use node:fs/promises instead.' },
    {
      name: 'node:stream',
      importNames: ['promises'],
      message: 'Use node:stream/promises instead.'
    },
    {
      name: 'node:timers',
      importNames: ['promises'],
      message: 'Use node:timers/promises instead.'
    }
  ],
  'no-restricted-properties': 'off',
  'no-restricted-syntax': [
    'error',
    {
      // `value.toString()`
      selector:
        'CallExpression[callee.property.name="toString"][callee.optional=false][arguments.length=0][optional=false]',
      message: 'Use String() instead.'
    },
    {
      selector: '[returnType.type="TSTypeAnnotation"]>TSTypeAnnotation>TSVoidKeyword',
      message: 'Use undefined for non-returning functions of unknown for callbacks'
    }
  ],
  'no-return-assign': ['error', 'always'],
  'no-return-await': 'error',
  'no-script-url': 'error',
  'no-sequences': ['error', { allowInParentheses: false }],
  'no-shadow': ['error', { hoist: 'all' }],
  'no-shadow-restricted-names': 'error',
  'no-ternary': 'off',
  'no-throw-literal': 'error',
  'no-undef-init': 'error',
  'no-undefined': 'off',
  'no-underscore-dangle': 'error',
  'no-unneeded-ternary': 'error',
  'no-unused-expressions': ['error', { enforceForJSX: true }],
  'no-unused-labels': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': 'error',
  'no-warning-comments': 'off',
  'no-with': 'error',
  'object-shorthand': ['error', 'always', { avoidExplicitReturnArrows: true }],
  'one-var': ['error', 'never'],
  'one-var-declaration-per-line': 'off',
  'operator-assignment': 'error',
  'prefer-arrow-callback': ['error', { allowUnboundThis: false }],
  'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
  'prefer-destructuring': [
    'error',
    {
      VariableDeclarator: { array: false, object: true },
      AssignmentExpression: { array: false, object: false }
    }
  ],
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'off',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'off',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'quote-props': 'off',
  radix: ['error', 'as-needed'],
  'require-await': 'error',
  'require-unicode-regexp': 'off',
  'require-yield': 'error',
  'sort-imports': ['error', { ignoreCase: true, ignoreDeclarationSort: true }],
  'sort-keys': 'off',
  'sort-vars': 'off',
  'spaced-comment': ['error', 'always', { block: { balanced: true } }],
  strict: 'error',
  'symbol-description': 'error',
  'vars-on-top': 'off',
  yoda: 'error'
}
